use_frameworks!

platform :ios, '12.0'

target 'PageState_Example' do
  pod 'PageState', :path => '../'
  pod 'SnapKit', '~> 5.7.0'

  target 'PageState_Tests' do
    inherit! :search_paths

    
  end
end
